[ups]
    driver = nutdrv_qx
    port = auto
    vendorid = 0001
    productid = 0000
    protocol = hunnox
    langid_fix = 0x0409
    novendor
    noscanlangid
    bus = "001"
    desc = "FinePower IEC LCD 3000VA"
